using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;
using System.Text.RegularExpressions;
using TFramework.Core;
using UnityEditor;
using UnityEngine;

namespace TFramework.MasterData.Editor
{
    /// <summary>
    /// MasterData関連のコードを生成するクラス
    /// データクラス、コンテナクラス、拡張メソッドを生成する
    /// </summary>
    public static class CodeGenerator
    {
        private const string GeneratedNamespace = "Game.MasterData.Generated";
        private const string SharedEnumFileName = "MasterDataEnums.generated.cs";
        private static readonly Dictionary<string, HashSet<string>> SharedEnumDefinitions = new Dictionary<string, HashSet<string>>();
        private static readonly Regex InvalidIdentifierRegex = new Regex(@"[^a-zA-Z0-9_]", RegexOptions.Compiled);

        /// <summary>
        /// 共有Enum定義の収集状態を初期化する
        /// </summary>
        public static void ResetSharedEnumDefinitions()
        {
            SharedEnumDefinitions.Clear();
        }

        /// <summary>
        /// CSVデータからコードを生成する
        /// </summary>
        public static void GenerateClass(string className, List<string[]> csvData, string outputPath)
        {
            if (csvData.Count < 3)
            {
                Debug.LogError($"[MasterData] CSVフォーマットが無効である: {className}");
                return;
            }

            // ディレクトリ作成
            if (!Directory.Exists(outputPath))
            {
                Directory.CreateDirectory(outputPath);
            }

            string[] variableNames = csvData[0];
            string[] descriptions = csvData[1];
            string[] types = csvData[2];

            Dictionary<int, string> enumTypeNames = RegisterEnumDefinitions(className, csvData, variableNames, types);

            GenerateGeneratedDataClass(className, variableNames, descriptions, types, enumTypeNames, outputPath);
            GenerateUserPartialClass(className, outputPath);
            GenerateContainerClass(className, types, outputPath);
        }

        /// <summary>
        /// 収集済みの共有Enum定義コードを出力する
        /// </summary>
        public static void GenerateSharedEnumFile(string outputPath)
        {
            if (SharedEnumDefinitions.Count == 0)
            {
                return;
            }

            StringBuilder sb = new StringBuilder();
            sb.AppendLine("// <auto-generated>");
            sb.AppendLine("// THIS CODE IS GENERATED BY TFRAMEWORK MASTERDATA IMPORTER.");
            sb.AppendLine("// DO NOT EDIT THIS FILE DIRECTLY.");
            sb.AppendLine("// </auto-generated>");
            sb.AppendLine();
            sb.AppendLine($"namespace {GeneratedNamespace}");
            sb.AppendLine("{");

            foreach ((string enumName, HashSet<string> values) in SharedEnumDefinitions.OrderBy(x => x.Key))
            {
                sb.AppendLine("    /// <summary>");
                sb.AppendLine($"    /// MasterData共有Enum: {enumName}");
                sb.AppendLine("    /// </summary>");
                sb.AppendLine($"    public enum {enumName}");
                sb.AppendLine("    {");

                foreach (string value in values.OrderBy(x => x))
                {
                    sb.AppendLine($"        {value},");
                }

                sb.AppendLine("    }");
                sb.AppendLine();
            }

            sb.AppendLine("}");

            File.WriteAllText(Path.Combine(outputPath, SharedEnumFileName), sb.ToString(), Encoding.UTF8);
        }

        /// <summary>
        /// データクラス（自動生成部分）を作成する
        /// </summary>
        private static void GenerateGeneratedDataClass(
            string className,
            string[] variableNames,
            string[] descriptions,
            string[] types,
            IReadOnlyDictionary<int, string> enumTypeNames,
            string outputPath)
        {
            StringBuilder sb = new StringBuilder();
            sb.AppendLine("// <auto-generated>");
            sb.AppendLine("// THIS CODE IS GENERATED BY TFRAMEWORK MASTERDATA IMPORTER.");
            sb.AppendLine("// DO NOT EDIT THIS FILE DIRECTLY.");
            sb.AppendLine("// </auto-generated>");
            sb.AppendLine();
            sb.AppendLine("using System;");
            sb.AppendLine("using System.Collections.Generic;");
            sb.AppendLine("using UnityEngine;");
            sb.AppendLine("using TFramework.MasterData;");
            sb.AppendLine();
            sb.AppendLine($"namespace {GeneratedNamespace}");
            sb.AppendLine("{");
            sb.AppendLine("    [Serializable]");
            sb.AppendLine($"    [MasterData(\"{className}\")]");

            string keyType = "int";
            string keyName = "Id";
            bool keyFound = false;

            for (int i = 0; i < types.Length; i++)
            {
                if (types[i] == "dummy")
                {
                    continue;
                }

                keyType = ConvertToCSharpType(types[i]);
                keyName = variableNames[i];
                keyFound = true;
                break;
            }

            if (!keyFound)
            {
                Debug.LogError($"[MasterData] 有効な列が見つからない: {className}");
                return;
            }

            sb.AppendLine($"    public partial class {className} : IMasterDataObject<{keyType}>");
            sb.AppendLine("    {");

            for (int i = 0; i < variableNames.Length; i++)
            {
                string type = types[i];
                if (type == "dummy")
                {
                    continue;
                }

                string name = variableNames[i];
                string desc = descriptions[i];

                string csharpType = IsEnumType(type)
                    ? enumTypeNames[i]
                    : ConvertToCSharpType(type);

                sb.AppendLine("        /// <summary>");
                sb.AppendLine($"        /// {desc}");
                sb.AppendLine("        /// </summary>");
                sb.AppendLine($"        public {csharpType} {name};");
                sb.AppendLine();
            }

            sb.AppendLine($"        public {keyType} GetKey() => {keyName};");
            sb.AppendLine("    }");
            sb.AppendLine("}");

            File.WriteAllText(Path.Combine(outputPath, $"{className}.generated.cs"), sb.ToString(), Encoding.UTF8);
        }

        /// <summary>
        /// Enum定義を登録するヘルパー
        /// </summary>
        private static Dictionary<int, string> RegisterEnumDefinitions(
            string className,
            List<string[]> csvData,
            string[] variableNames,
            string[] types)
        {
            Dictionary<int, string> enumTypeNames = new Dictionary<int, string>();

            for (int col = 0; col < types.Length; col++)
            {
                if (!IsEnumType(types[col]))
                {
                    continue;
                }

                string enumName = ResolveEnumTypeName(className, variableNames[col], types[col]);
                if (!SharedEnumDefinitions.TryGetValue(enumName, out HashSet<string> values))
                {
                    values = new HashSet<string>();
                    SharedEnumDefinitions[enumName] = values;
                }

                for (int row = 3; row < csvData.Count; row++)
                {
                    if (col >= csvData[row].Length)
                    {
                        continue;
                    }

                    string rawValue = csvData[row][col];
                    if (string.IsNullOrWhiteSpace(rawValue))
                    {
                        continue;
                    }

                    values.Add(SanitizeIdentifier(rawValue));
                }

                enumTypeNames[col] = enumName;
            }

            return enumTypeNames;
        }

        private static void GenerateUserPartialClass(string className, string outputPath)
        {
            string path = Path.Combine(outputPath, $"{className}.cs");
            if (File.Exists(path))
            {
                return;
            }

            StringBuilder sb = new StringBuilder();
            sb.AppendLine("using System.Linq;");
            sb.AppendLine("using TFramework.MasterData;");
            sb.AppendLine();
            sb.AppendLine($"namespace {GeneratedNamespace}");
            sb.AppendLine("{");
            sb.AppendLine($"    public partial class {className}");
            sb.AppendLine("    {");
            sb.AppendLine("        // ここに拡張メソッドや計算プロパティを記述する");
            sb.AppendLine("    }");
            sb.AppendLine("}");

            File.WriteAllText(path, sb.ToString(), Encoding.UTF8);
        }

        private static void GenerateContainerClass(string className, string[] types, string outputPath)
        {
            string keyType = "int";
            foreach (string type in types)
            {
                if (type == "dummy")
                {
                    continue;
                }

                keyType = ConvertToCSharpType(type);
                break;
            }

            string containerName = $"{className}Container";
            StringBuilder sb = new StringBuilder();

            sb.AppendLine("// <auto-generated>");
            sb.AppendLine("// THIS CODE IS GENERATED BY TFRAMEWORK MASTERDATA IMPORTER.");
            sb.AppendLine("// </auto-generated>");
            sb.AppendLine();
            sb.AppendLine("using System;");
            sb.AppendLine("using System.Collections.Generic;");
            sb.AppendLine("using System.Linq;");
            sb.AppendLine("using UnityEngine;");
            sb.AppendLine("using TFramework.MasterData;");
            sb.AppendLine();
            sb.AppendLine($"namespace {GeneratedNamespace}");
            sb.AppendLine("{");
            sb.AppendLine($"    [CreateAssetMenu(fileName = \"{containerName}\", menuName = \"TFramework/MasterData/{className}\")]");
            sb.AppendLine($"    public class {containerName} : ScriptableObject");
            sb.AppendLine("    {");
            sb.AppendLine($"        [SerializeField] private List<{className}> _data = new List<{className}>();");
            sb.AppendLine();
            sb.AppendLine($"        public IReadOnlyList<{className}> All => _data;");
            sb.AppendLine();
            sb.AppendLine($"        public {className} Find({keyType} id)");
            sb.AppendLine("        {");
            sb.AppendLine("            return _data.FirstOrDefault(x => x.GetKey().Equals(id));");
            sb.AppendLine("        }");
            sb.AppendLine();
            sb.AppendLine("        // Editor用データ注入メソッド");
            sb.AppendLine($"        internal void SetData(List<{className}> data)");
            sb.AppendLine("        {");
            sb.AppendLine("            _data = data;");
            sb.AppendLine("        }");
            sb.AppendLine("    }");
            sb.AppendLine("}");

            File.WriteAllText(Path.Combine(outputPath, $"{containerName}.cs"), sb.ToString(), Encoding.UTF8);
        }

        /// <summary>
        /// IMasterDataServiceの拡張メソッドを生成する
        /// これにより _masterData.CharacterMasterData() のようなアクセスが可能になる
        /// </summary>
        public static void GenerateServiceExtensions(List<string> classNames, string outputPath)
        {
            StringBuilder sb = new StringBuilder();
            sb.AppendLine("// <auto-generated>");
            sb.AppendLine("// THIS CODE IS GENERATED BY TFRAMEWORK MASTERDATA IMPORTER.");
            sb.AppendLine("// </auto-generated>");
            sb.AppendLine();
            sb.AppendLine("using TFramework.MasterData;");
            sb.AppendLine($"using {GeneratedNamespace};");
            sb.AppendLine();
            sb.AppendLine($"namespace {GeneratedNamespace}");
            sb.AppendLine("{");
            sb.AppendLine("    public static class MasterDataServiceExtensions");
            sb.AppendLine("    {");
            foreach (string name in classNames)
            {
                sb.AppendLine($"        public static {name}Container {name}(this IMasterDataService self)");
                sb.AppendLine("        {");
                sb.AppendLine($"            return self.GetContainer<{name}Container>();");
                sb.AppendLine("        }");
                sb.AppendLine();
            }
            sb.AppendLine("    }");
            sb.AppendLine("}");

            File.WriteAllText(Path.Combine(outputPath, "MasterDataServiceExtensions.Generated.cs"), sb.ToString(), Encoding.UTF8);
        }

        private static string ConvertToCSharpType(string csvType)
        {
            if (IsEnumType(csvType))
            {
                return "int";
            }

            return csvType.ToLower() switch
            {
                "int" => "int",
                "long" => "long",
                "float" => "float",
                "string" => "string",
                "bool" => "bool",
                "datetime" => "DateTime",
                _ => "string"
            };
        }

        /// <summary>
        /// Enum型指定か判定する
        /// </summary>
        private static bool IsEnumType(string csvType)
        {
            return !string.IsNullOrEmpty(csvType) && (csvType == "enum" || csvType.StartsWith("enum:"));
        }

        /// <summary>
        /// CSV型指定からEnum型名を解決する
        /// </summary>
        private static string ResolveEnumTypeName(string className, string variableName, string csvType)
        {
            if (string.IsNullOrEmpty(csvType) || csvType == "enum")
            {
                return $"{className}{SanitizeIdentifier(variableName)}Enum";
            }

            string rawEnumName = csvType.Substring("enum:".Length);
            return SanitizeIdentifier(rawEnumName);
        }

        /// <summary>
        /// C#識別子として安全な形式へ正規化する
        /// </summary>
        private static string SanitizeIdentifier(string rawValue)
        {
            if (string.IsNullOrWhiteSpace(rawValue))
            {
                return "_";
            }

            string trimmed = rawValue.Trim();
            string normalized = InvalidIdentifierRegex.Replace(trimmed, "_");
            if (char.IsDigit(normalized[0]))
            {
                normalized = $"_{normalized}";
            }

            return normalized;
        }
    }
}
