using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;
using TFramework.Core;
using UnityEditor;
using UnityEngine;

namespace TFramework.MasterData.Editor
{
    /// <summary>
    /// MasterData関連のコードを生成するクラス
    /// データクラス、コンテナクラス、拡張メソッドを生成する
    /// </summary>
    public static class CodeGenerator
    {
        private const string GeneratedNamespace = "Game.MasterData.Generated";

        /// <summary>
        /// CSVデータからコードを生成する
        /// </summary>
        public static void GenerateClass(string className, List<string[]> csvData, string outputPath)
        {
            if (csvData.Count < 3)
            {
                Debug.LogError($"[MasterData] CSVフォーマットが無効である: {className}");
                return;
            }

            // ディレクトリ作成
            if (!Directory.Exists(outputPath))
            {
                Directory.CreateDirectory(outputPath);
            }

            var variableNames = csvData[0];
            var descriptions = csvData[1];
            var types = csvData[2];

            // Enum定義の生成が必要な列を特定し、Enum定義コードを生成する
            var enumDefinitions = GenerateEnumDefinitions(className, csvData, variableNames, types);

            // Generatedクラスの生成
            GenerateGeneratedDataClass(className, variableNames, descriptions, types, enumDefinitions, outputPath);

            // User Partialクラスの生成
            GenerateUserPartialClass(className, outputPath);

            // Containerクラスの生成
            GenerateContainerClass(className, types, outputPath);
        }

        /// <summary>
        /// データクラス（自動生成部分）を作成する
        /// </summary>
        private static void GenerateGeneratedDataClass(
            string className, 
            string[] variableNames, 
            string[] descriptions, 
            string[] types, 
            Dictionary<int, string> enumDefinitions,
            string outputPath)
        {
            var sb = new StringBuilder();
            sb.AppendLine("// <auto-generated>");
            sb.AppendLine("// THIS CODE IS GENERATED BY TFRAMEWORK MASTERDATA IMPORTER.");
            sb.AppendLine("// DO NOT EDIT THIS FILE DIRECTLY.");
            sb.AppendLine("// </auto-generated>");
            sb.AppendLine();
            sb.AppendLine("using System;");
            sb.AppendLine("using System.Collections.Generic;");
            sb.AppendLine("using UnityEngine;");
            sb.AppendLine("using TFramework.MasterData;");
            sb.AppendLine();
            sb.AppendLine($"namespace {GeneratedNamespace}");
            sb.AppendLine("{");
            sb.AppendLine("    [Serializable]");
            sb.AppendLine($"    [MasterData(\"{className}\")]");

            string keyType = "int";
            string keyName = "Id";
            bool keyFound = false;

            // メインキー検索
            for (int i = 0; i < types.Length; i++)
            {
                if (types[i] == "dummy") continue;
                keyType = ConvertToCSharpType(types[i]);
                keyName = variableNames[i];
                keyFound = true;
                break;
            }

            if (!keyFound)
            {
                Debug.LogError($"[MasterData] 有効な列が見つからない: {className}");
                return;
            }

            sb.AppendLine($"    public partial class {className} : IMasterDataObject<{keyType}>");
            sb.AppendLine("    {");

            // Enum定義の埋め込み
            if (enumDefinitions.Count > 0)
            {
                foreach (var enumDef in enumDefinitions.Values)
                {
                    sb.AppendLine(enumDef);
                }
                sb.AppendLine();
            }

            // プロパティ生成
            for (int i = 0; i < variableNames.Length; i++)
            {
                var type = types[i];
                if (type == "dummy") continue;

                var name = variableNames[i];
                var desc = descriptions[i];
                
                string csharpType;
                if (type == "enum")
                {
                    csharpType = $"{className}{name}Enum"; // ネストされたEnum名
                }
                else
                {
                    csharpType = ConvertToCSharpType(type);
                }

                sb.AppendLine($"        /// <summary>");
                sb.AppendLine($"        /// {desc}");
                sb.AppendLine($"        /// </summary>");
                sb.AppendLine($"        public {csharpType} {name};");
                sb.AppendLine();
            }

            // GetKey実装
            sb.AppendLine($"        public {keyType} GetKey() => {keyName};");
            sb.AppendLine("    }");
            sb.AppendLine("}");

            File.WriteAllText(Path.Combine(outputPath, $"{className}.generated.cs"), sb.ToString(), Encoding.UTF8);
        }

        // Enum定義を生成するヘルパー
        private static Dictionary<int, string> GenerateEnumDefinitions(string className, List<string[]> csvData, string[] variableNames, string[] types)
        {
            var enums = new Dictionary<int, string>();
            
            for (int col = 0; col < types.Length; col++)
            {
                if (types[col] != "enum") continue;

                var enumName = $"{className}{variableNames[col]}Enum";
                var uniqueValues = new HashSet<string>();

                // 4行目以降のデータをスキャン
                for (int row = 3; row < csvData.Count; row++)
                {
                    if (row >= csvData.Count || col >= csvData[row].Length) continue;
                    var val = csvData[row][col];
                    if (!string.IsNullOrEmpty(val))
                    {
                        uniqueValues.Add(val);
                    }
                }

                var sb = new StringBuilder();
                sb.AppendLine($"        public enum {enumName}");
                sb.AppendLine("        {");
                foreach (var val in uniqueValues)
                {
                    // 数値で始まる場合などはプレフィックスが必要だが、今回はそのまま使用可能と仮定
                    // 空白除去などは行う
                    var cleanVal = val.Trim();
                    if (!string.IsNullOrEmpty(cleanVal))
                    {
                        sb.AppendLine($"            {cleanVal},");
                    }
                }
                sb.AppendLine("        }");
                
                enums[col] = sb.ToString(); 
            }
            return enums;
        }

        private static void GenerateUserPartialClass(string className, string outputPath)
        {
            var path = Path.Combine(outputPath, $"{className}.cs");
            if (File.Exists(path)) return;

            var sb = new StringBuilder();
            sb.AppendLine("using System.Linq;");
            sb.AppendLine("using TFramework.MasterData;");
            sb.AppendLine();
            sb.AppendLine($"namespace {GeneratedNamespace}");
            sb.AppendLine("{");
            sb.AppendLine($"    public partial class {className}");
            sb.AppendLine("    {");
            sb.AppendLine("        // ここに拡張メソッドや計算プロパティを記述する");
            sb.AppendLine("    }");
            sb.AppendLine("}");

            File.WriteAllText(path, sb.ToString(), Encoding.UTF8);
        }

        private static void GenerateContainerClass(string className, string[] types, string outputPath)
        {
            // メインキーの型を特定
            string keyType = "int";
            foreach (var t in types)
            {
                if (t != "dummy")
                {
                    keyType = ConvertToCSharpType(t);
                    break;
                }
            }

            var containerName = $"{className}Container";
            var sb = new StringBuilder();
            
            sb.AppendLine("// <auto-generated>");
            sb.AppendLine("// THIS CODE IS GENERATED BY TFRAMEWORK MASTERDATA IMPORTER.");
            sb.AppendLine("// </auto-generated>");
            sb.AppendLine();
            sb.AppendLine("using System;");
            sb.AppendLine("using System.Collections.Generic;");
            sb.AppendLine("using System.Linq;");
            sb.AppendLine("using UnityEngine;");
            sb.AppendLine("using TFramework.MasterData;");
            sb.AppendLine();
            sb.AppendLine($"namespace {GeneratedNamespace}");
            sb.AppendLine("{");
            sb.AppendLine($"    [CreateAssetMenu(fileName = \"{containerName}\", menuName = \"TFramework/MasterData/{className}\")]");
            sb.AppendLine($"    public class {containerName} : ScriptableObject");
            sb.AppendLine("    {");
            sb.AppendLine($"        [SerializeField] private List<{className}> _data = new List<{className}>();");
            sb.AppendLine();
            sb.AppendLine($"        public IReadOnlyList<{className}> All => _data;");
            sb.AppendLine();
            sb.AppendLine($"        public {className} Find({keyType} id)");
            sb.AppendLine("        {");
            // シンプルな線形探索。必要ならDictionaryキャッシュを実装する
            sb.AppendLine($"            return _data.FirstOrDefault(x => x.GetKey().Equals(id));");
            sb.AppendLine("        }");
            sb.AppendLine();
            sb.AppendLine($"        // Editor用データ注入メソッド");
            sb.AppendLine($"        internal void SetData(List<{className}> data)");
            sb.AppendLine("        {");
            sb.AppendLine("            _data = data;");
            sb.AppendLine("        }");
            sb.AppendLine("    }");
            sb.AppendLine("}");

            File.WriteAllText(Path.Combine(outputPath, $"{containerName}.cs"), sb.ToString(), Encoding.UTF8);
        }

        /// <summary>
        /// IMasterDataServiceの拡張メソッドを生成する
        /// これにより _masterData.CharacterMasterData() のようなアクセスが可能になる
        /// </summary>
        public static void GenerateServiceExtensions(List<string> classNames, string outputPath)
        {
            var sb = new StringBuilder();
            sb.AppendLine("// <auto-generated>");
            sb.AppendLine("// THIS CODE IS GENERATED BY TFRAMEWORK MASTERDATA IMPORTER.");
            sb.AppendLine("// </auto-generated>");
            sb.AppendLine();
            sb.AppendLine("using TFramework.MasterData;");
            sb.AppendLine($"using {GeneratedNamespace};");
            sb.AppendLine();
            sb.AppendLine($"namespace {GeneratedNamespace}");
            sb.AppendLine("{");
            sb.AppendLine("    public static class MasterDataServiceExtensions");
            sb.AppendLine("    {");
            foreach (var name in classNames)
            {
                sb.AppendLine($"        public static {name}Container {name}(this IMasterDataService self)");
                sb.AppendLine("        {");
                sb.AppendLine($"            return self.GetContainer<{name}Container>();");
                sb.AppendLine("        }");
                sb.AppendLine();
            }
            sb.AppendLine("    }");
            sb.AppendLine("}");

            File.WriteAllText(Path.Combine(outputPath, "MasterDataServiceExtensions.Generated.cs"), sb.ToString(), Encoding.UTF8);
        }

        private static string ConvertToCSharpType(string csvType)
        {
            return csvType.ToLower() switch
            {
                "int" => "int",
                "long" => "long",
                "float" => "float",
                "string" => "string",
                "bool" => "bool",
                "datetime" => "DateTime",
                "enum" => "int", // Enum自体は別関数で処理されるが、デフォルトとしてintを返す
                _ => "string"
            };
        }
    }
}
