using UnityEditor;
using UnityEngine;
using System.IO;
using System.Text;
using TFramework.Debug;

namespace TFramework.Network.Editor
{
    /// <summary>
    /// NetworkSettingsの設定値から環境切り替え用の動的メニューを生成する
    /// </summary>
    public static class NetworkMenuGenerator
    {
        private const string GeneratedFilePath = "Assets/Scripts/Generated/Network/Editor/NetworkEnvironmentMenuItems.cs";

        public static void Generate()
        {
            var settings = NetworkSettings.Instance;
            if (settings == null) return;

            var sb = new StringBuilder();
            sb.AppendLine("// <auto-generated>");
            sb.AppendLine("// THIS CODE IS GENERATED BY TFRAMEWORK (NetworkMenuGenerator).");
            sb.AppendLine("// DO NOT EDIT DIRECTLY.");
            sb.AppendLine("// </auto-generated>");
            sb.AppendLine();
            sb.AppendLine("using UnityEditor;");
            sb.AppendLine("using TFramework.Network;");
            sb.AppendLine("using TFramework.Network.Editor;");
            sb.AppendLine();
            sb.AppendLine("namespace Game.Network.Generated.Editor");
            sb.AppendLine("{");
            sb.AppendLine("    public static class NetworkEnvironmentMenuItems");
            sb.AppendLine("    {");

            foreach (var env in settings.Environments)
            {
                if (string.IsNullOrEmpty(env.Name)) continue;
                
                // メソッド名として安全な文字列に変換
                string safeName = env.Name.Replace(" ", "_").Replace("-", "_").Replace(".", "_");
                
                sb.AppendLine($"        [MenuItem(\"TFramework/Network/Environments/{env.Name}\", false, 50)]");
                sb.AppendLine($"        public static void SwitchTo_{safeName}()");
                sb.AppendLine("        {");
                sb.AppendLine($"            NetworkEnvironmentSwitcher.SwitchEnvironment(\"{env.Name}\");");
                sb.AppendLine("        }");
                sb.AppendLine();
                
                // メニューのチェックマーク状態を更新するためのValidateメソッド
                sb.AppendLine($"        [MenuItem(\"TFramework/Network/Environments/{env.Name}\", true)]");
                sb.AppendLine($"        public static bool Validate_{safeName}()");
                sb.AppendLine("        {");
                sb.AppendLine($"            var settings = NetworkSettings.Instance;");
                sb.AppendLine($"            bool isActive = settings != null && settings.CurrentEnvironment == \"{env.Name}\";");
                sb.AppendLine($"            Menu.SetChecked(\"TFramework/Network/Environments/{env.Name}\", isActive);");
                sb.AppendLine($"            return true;");
                sb.AppendLine("        }");
                sb.AppendLine();
            }

            sb.AppendLine("    }");
            sb.AppendLine("}");

            // 出力先ディレクトリが存在しない場合は作成する
            var outputDir = Path.GetDirectoryName(GeneratedFilePath);
            if (!Directory.Exists(outputDir))
            {
                Directory.CreateDirectory(outputDir);
            }

            File.WriteAllText(GeneratedFilePath, sb.ToString());
            AssetDatabase.ImportAsset(GeneratedFilePath);
            
            TLogger.Info("環境切り替えメニューを再生成しました (コンパイル後に反映されます)。");
        }
    }
}
